### ISSUE TITLE
Update the module structure to work with Drupal 8 Composer requirement

### ISSUE THREAD

**Issue by stewest** [Payfast/drupalcommerce-aggregation#2]
Hi. Thanks to the original drupal devs and Payfast devs for making this module available for Drupal 8.

With Drupal 8 we begin to see recommendations for using Composer for installing contrib modules and their dependencies
https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies

I've forked and updated your repo here, and tested it
https://github.com/stewest/commerce_payfast

Perhaps you'd want to make a Composer branch option on this repo?

**Comment by RheinhardtSnyman** [comment]
Hi, thank you for your suggestion. 

We have added composer support for this module. 

For further assistance please contact support@payfast.co.za
