### ISSUE TITLE
Payment status is not set to complete

### ISSUE THREAD

**Issue by VlooiVlerke** [Payfast/drupalcommerce-aggregation#5]
After payment has been made successfully the payment status is set to "new" instead of "completed"
According to drupal
[https://docs.drupalcommerce.org/v2/developer-guide/payments/creating-payment-gateway/#capturing-payments-authorizations](url)

`$payment->setState('completed');`

Should be set after a payment was made successfully.
Instead payfast sets the payment state to "new".

I tried adding 
`$payment->setState('completed');`

to 

`//// Check status and update order
        if (!$pfError) {

            pflog('Check status and update order');

            if ($pfData['payment_status'] == 'COMPLETE') {

              $payment_storage = $this->entityTypeManager->getStorage('commerce_payment');
              $payment = $payment_storage->create([
                'state' => 'completed',
                'amount' => $pfData['amount_gross'],
                'payment_gateway' => $this->parentEntity->id(),
                'order_id' => $pfData['custom_int1'],
                'remote_id' => $pfData['pf_payment_id'],
                'remote_state' =>  $pfData['payment_status'],
              ]);
			  $payment->setState('completed');
              $payment->setRefundedAmount(new Price(0.00, 'ZAR'));
              $payment->setAmount(new Price($pfData['amount_gross'], 'ZAR'));
              $payment->save();
            }
        }

        if ($pfError) {
            pflog('Error: ' . $pfErrMsg);
        }
    }
}`

But this did not work. 
All payments received are set to "new" and a "payment complete" date does not show under the order payment details.

**Comment by VlooiVlerke** [comment]
Hi, Is there any update on this issue. 

This is causing major problems. Failed payments also show up as new payment in the drupal order console

**Comment by bruce-atkinson** [comment]
Please note this issue has been resolved in the latest release, 1.4.0 https://github.com/Payfast/mod-drupalcommerce/pull/7. 

The module is also now compatible with Drupal 10.
