### ISSUE TITLE
PayFast is Drupal 10 ready

### ISSUE THREAD

**Issue by VlooiVlerke** [Payfast/drupalcommerce-aggregation#6]
I tested PayFast using Drupal 10 install and it works

Simply add drupal 10 to commerce_payfast.info.yml

`core_version_requirement: ^8 || ^9 || ^10`

**Comment by bruce-atkinson** [comment]
Please note this issue has been resolved in the latest release, 1.4.0 https://github.com/Payfast/mod-drupalcommerce/pull/7. 

The module is also now compatible with Drupal 10.
